fix msvc error C2955: 'jinja2::IndexedEnumeratorImpl': use of class template requires template argument list (#276)
* fix msvc error C2955: 'jinja2::IndexedEnumeratorImpl': use of class template requires template argument list

* fix compilation error C3210